[phases.setup]
nixPkgs = ["...", "bash"]

[phases.install]
cmds = ["bun i --no-save"]

[phases.build]
cmds = ["bash create-stubs.sh", "bun run build", "bash fix-imports.sh"]

[start]
cmd = "bun run start"
